2019-07-15 11:09:48,526 ERROR 22335 [-/::1/-/13ms GET /news] nodejs.TypeError: dataList.map is not a function
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:21)
    at NewsController.list (/Users/xieww/Desktop/aries-web/service/app/controller/news.js:7:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)
    at /Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)

pid: 22335
hostname: ali.local

2019-07-15 11:20:09,253 ERROR 24401 [-/::1/-/139ms GET /news] nodejs.TypeError: Cannot read property 'subjects' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 24401
hostname: ali.local

2019-07-15 11:21:02,940 ERROR 24577 [-/::1/-/141ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 24577
hostname: ali.local

2019-07-15 11:21:29,528 ERROR 24656 [-/::1/-/180ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:18:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 24656
hostname: ali.local

2019-07-15 11:21:30,577 ERROR 24656 [-/::1/-/47ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:18:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 24656
hostname: ali.local

2019-07-15 11:22:10,733 ERROR 24802 [-/::1/-/11ms GET /news] nodejs.TypeError: Cannot create property 'ctx' on string '{"type":"movie","tag":"热门","page_limit":50,"page_start":0}'
    at ContextHttpClient.curl (/Users/xieww/Desktop/aries-web/service/node_modules/egg/lib/core/context_httpclient.js:19:17)
    at Object.curl (/Users/xieww/Desktop/aries-web/service/node_modules/egg/app/extend/context.js:48:28)
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:11:56)
    at NewsController.list (/Users/xieww/Desktop/aries-web/service/app/controller/news.js:7:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)

pid: 24802
hostname: ali.local

2019-07-15 11:22:59,027 ERROR 24954 [-/::1/-/8ms GET /news] nodejs.TypeError: Cannot create property 'ctx' on string 'type: 'movie', tag: '热门', page_limit: 50, page_start: 0'
    at ContextHttpClient.curl (/Users/xieww/Desktop/aries-web/service/node_modules/egg/lib/core/context_httpclient.js:19:17)
    at Object.curl (/Users/xieww/Desktop/aries-web/service/node_modules/egg/app/extend/context.js:48:28)
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:11:56)
    at NewsController.list (/Users/xieww/Desktop/aries-web/service/app/controller/news.js:7:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)

pid: 24954
hostname: ali.local

2019-07-15 11:23:01,073 ERROR 24954 [-/::1/-/1ms GET /news] nodejs.TypeError: Cannot create property 'ctx' on string 'type: 'movie', tag: '热门', page_limit: 50, page_start: 0'
    at ContextHttpClient.curl (/Users/xieww/Desktop/aries-web/service/node_modules/egg/lib/core/context_httpclient.js:19:17)
    at Object.curl (/Users/xieww/Desktop/aries-web/service/node_modules/egg/app/extend/context.js:48:28)
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:11:56)
    at NewsController.list (/Users/xieww/Desktop/aries-web/service/app/controller/news.js:7:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)

pid: 24954
hostname: ali.local

2019-07-15 11:23:18,818 ERROR 25037 [-/::1/-/126ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:18:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 25037
hostname: ali.local

2019-07-15 11:23:39,600 ERROR 25109 [-/::1/-/153ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 25109
hostname: ali.local

2019-07-15 11:24:15,792 ERROR 25242 [-/::1/-/131ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 25242
hostname: ali.local

2019-07-15 11:24:49,232 ERROR 25362 [-/::1/-/158ms GET /news] nodejs.TypeError: Cannot read property 'map' of undefined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 25362
hostname: ali.local

2019-07-15 11:27:03,060 ERROR 25825 [-/::1/-/154ms GET /news] nodejs.ReferenceError: movieList is not defined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 25825
hostname: ali.local

2019-07-15 11:34:32,628 ERROR 27223 [-/::1/-/165ms GET /news] nodejs.ReferenceError: movieList is not defined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:19:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 27223
hostname: ali.local

2019-07-15 11:35:35,300 ERROR 27430 [-/::1/-/492ms GET /news] nodejs.ReferenceError: movieList is not defined
    at NewsService.list (/Users/xieww/Desktop/aries-web/service/app/service/news.js:21:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 27430
hostname: ali.local

2019-07-15 16:51:55,171 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 796793ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 18:17:55,307 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 1572211ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 18:35:57,168 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 981822ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 19:30:45,267 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 1443773ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 20:02:26,204 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 276249ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 20:34:11,683 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 1865464ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 21:05:27,425 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 1815722ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 21:41:58,948 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 2151402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-15 23:44:28,880 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 7209742ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 01:45:23,842 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 7211078ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 03:46:19,877 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 7212016ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 05:47:16,893 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 7212995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 07:48:30,355 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 7213185ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 09:35:15,688 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 6357207ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 09:39:27,119 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 211368ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 10:11:16,844 ERROR 22851 nodejs.ClusterClientNoResponseError: client no response in 1226015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 22851
hostname: ali.local

2019-07-16 11:40:07,987 ERROR 99097 [-/::1/-/6ms GET /news] nodejs.TypeError: Cannot read property 'getMovieList' of undefined
    at NewsController.list (/Users/xieww/Desktop/aries-web/service/app/controller/news.js:7:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)
    at /Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at /Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:36:12

pid: 99097
hostname: ali.local

2019-07-16 11:46:51,597 ERROR 724 [-/::1/-/3400ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find view/list.tpl from /Users/xieww/Desktop/aries-web/service/app/view
    at Map.resolve (/Users/xieww/Desktop/aries-web/service/node_modules/egg-view/lib/view_manager.js:74:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 724
hostname: ali.local

2019-07-16 15:19:17,592 ERROR 28274 nodejs.ClusterClientNoResponseError: client no response in 2183842ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28274
hostname: ali.local

2019-07-16 15:43:17,846 ERROR 28724 [-/::1/-/1ms GET /movie/douban?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0] nodejs.ReferenceError: serverUrl is not defined
    at NewsService.getDoubanData (/Users/xieww/Desktop/aries-web/service/app/service/movie.js:22:36)
    at NewsController.getMovieList (/Users/xieww/Desktop/aries-web/service/app/controller/movie.js:12:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)
    at /Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)

pid: 28724
hostname: ali.local

2019-07-16 15:48:24,259 ERROR 28748 [-/::1/-/10ms GET /movie/douban?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0] nodejs.ReferenceError: serverUrl is not defined
    at NewsService.getDoubanData (/Users/xieww/Desktop/aries-web/service/app/service/movie.js:22:36)
    at NewsController.getMovieList (/Users/xieww/Desktop/aries-web/service/app/controller/movie.js:12:46)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xieww/Desktop/aries-web/service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:45:18)
    at /Users/xieww/Desktop/aries-web/service/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xieww/Desktop/aries-web/service/node_modules/koa-compose/index.js:44:32)

pid: 28748
hostname: ali.local

2019-07-16 15:49:36,926 ERROR 28787 [-/::1/-/453ms GET /movie/douban?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0] nodejs.TypeError: this.success is not a function
    at NewsController.getMovieList (/Users/xieww/Desktop/aries-web/service/app/controller/movie.js:14:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 28787
hostname: ali.local

2019-07-16 15:49:39,567 ERROR 28787 [-/::1/-/275ms GET /movie/douban?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0] nodejs.TypeError: this.success is not a function
    at NewsController.getMovieList (/Users/xieww/Desktop/aries-web/service/app/controller/movie.js:14:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 28787
hostname: ali.local

2019-07-16 15:51:05,104 ERROR 28832 [-/::1/-/429ms GET /movie/douban?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0] nodejs.TypeError: this.success is not a function
    at NewsController.getMovieList (/Users/xieww/Desktop/aries-web/service/app/controller/movie.js:14:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 28832
hostname: ali.local

2019-07-16 15:51:25,982 ERROR 28846 [-/::1/-/392ms GET /movie/douban?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0] nodejs.TypeError: this.success is not a function
    at NewsController.getMovieList (/Users/xieww/Desktop/aries-web/service/app/controller/movie.js:14:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 28846
hostname: ali.local

2019-07-16 16:05:14,117 ERROR 28902 [-/::1/-/1ms GET /public/dist/main.min.css] nodejs.ENOENTError: ENOENT: no such file or directory, stat '/Users/xieww/Desktop/aries-web/service/app/public/dist/main.min.css'
ENOENTError: ENOENT: no such file or directory, stat '/Users/xieww/Desktop/aries-web/service/app/public/dist/main.min.css'
errno: -2
code: "ENOENT"
syscall: "stat"
path: "/Users/xieww/Desktop/aries-web/service/app/public/dist/main.min.css"
name: "ENOENTError"
pid: 28902
hostname: ali.local

2019-07-16 16:05:14,166 ERROR 28902 [-/::1/-/51ms GET /public/dist/bundle.js] nodejs.ENOENTError: ENOENT: no such file or directory, stat '/Users/xieww/Desktop/aries-web/service/app/public/dist/bundle.js'
ENOENTError: ENOENT: no such file or directory, stat '/Users/xieww/Desktop/aries-web/service/app/public/dist/bundle.js'
errno: -2
code: "ENOENT"
syscall: "stat"
path: "/Users/xieww/Desktop/aries-web/service/app/public/dist/bundle.js"
name: "ENOENTError"
pid: 28902
hostname: ali.local

2019-07-16 17:01:31,348 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 1900954ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 17:10:58,566 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 487178ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 17:41:11,490 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 592567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 18:23:40,144 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 1843991ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 18:43:55,107 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 1114929ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 19:09:16,406 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 176932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 20:50:42,696 ERROR 28831 nodejs.ClusterClientNoResponseError: client no response in 1061222ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 28831
hostname: ali.local

2019-07-16 21:18:01,176 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 916021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-16 21:57:40,001 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 2338676ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-16 23:59:54,381 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 7209585ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 02:01:09,050 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 7214626ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 02:58:06,702 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 3377584ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 04:59:03,424 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 7216673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 05:04:23,783 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 280331ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 07:05:22,228 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 7218398ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 09:05:59,782 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 7217467ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 09:35:06,769 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 1686742ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 10:10:58,328 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 2111517ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 10:38:37,026 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 770597ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 11:33:36,320 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 2058791ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 12:21:36,459 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 2820112ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 13:05:30,107 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 1413015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 14:11:23,799 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 2733181ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 15:54:13,812 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 5669698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

2019-07-17 16:20:58,821 ERROR 30679 nodejs.ClusterClientNoResponseError: client no response in 364347ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xieww/Desktop/aries-web/service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30679
hostname: ali.local

